spring:
  data:
    redis:
      host: ${nft.turbo.redis.url}
      port: ${nft.turbo.redis.port}
      password: ${nft.turbo.redis.password}
      ssl:
        enabled: true
  redis:
    redisson:
      config: |
        singleServerConfig:
          idleConnectionTimeout: 10000
          connectTimeout: 10000
          timeout: 3000
          retryAttempts: 3
          retryInterval: 1500
          password: ${nft.turbo.redis.password}
          subscriptionsPerConnection: 5
          clientName: null
          address: "redis://${nft.turbo.redis.url}:${nft.turbo.redis.port}"
          subscriptionConnectionMinimumIdleSize: 1
          subscriptionConnectionPoolSize: 50
          connectionMinimumIdleSize: 24
          connectionPoolSize: 64
          database: 0
          dnsMonitoringInterval: 5000
        threads: 16
        nettyThreads: 32
        codec: !<org.redisson.client.codec.StringCodec> {}
        transportMode: "NIO"

# JetCache缓存配置
jetcache:
  # 统计信息收集间隔时间(分钟)
  statIntervalMinutes: 1
  # 缓存名称中是否包含区域信息
  areaInCacheName: false
  # 本地缓存配置
  local:
    default:
      # 缓存类型为Caffeine
      type: caffeine
      # 键转换器使用fastjson2
      keyConvertor: fastjson2
  # 远程缓存配置
  remote:
    default:
      # 缓存类型为Redisson
      type: redisson
      # 键转换器使用fastjson2
      keyConvertor: fastjson2
      # 广播频道名称，使用应用名称
      broadcastChannel: ${spring.application.name}
      # 键前缀，使用应用名称
      keyPrefix: ${spring.application.name}
      # 值编码器使用Java序列化
      valueEncoder: java
      # 值解码器使用Java反序列化
      valueDecoder: java
      # 默认过期时间(毫秒)
      defaultExpireInMillis: 5000
