spring:
  cloud:
    stream:
      rocketmq:
        binder:
          name-server: ${nft.turbo.rocketmq.url}
rocketmq:
  name-server: ${nft.turbo.rocketmq.url}
  broker:
    check: true
    #false 单条消费MQ的newBuy消息，但是消息会无法发送和消费
    #true  批量消费MQ的newBuy消息