spring:
  cloud:
    stream:
      rocketmq:
        binder:
          name-server: ${nft.turbo.rocketmq.url}
rocketmq:
  name-server: ${nft.turbo.rocketmq.url}
  broker:
    check: true
    # 项目中有两种方式使用了RocketMQ，其中通过SpringCloud Stream方式对MQ不强依赖，
    # 即使没部署RocketMQ应用也能正常启动，但是另外一种通过MQ Client的方式则强依赖RocketMQ的部署，所以这里是用来控制避免对RocketMQ强依赖的。
