spring:
  profiles:
    active: prod
  application:
    name: @application.name@
  config:
    import: classpath:base.yml,classpath:datasource.yml,classpath:rpc.yml,classpath:cache.yml,classpath:job.yml,classpath:seata.yml

server:
  port: 8088